language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .
script:
  - isort --project country_converter --profile black --check-only .
  - coverage run pytest --black -vv country_converter
after_success:
    coveralls
