language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pytest-pep8
  - pip install .
  - pip install pytest-cov python-coveralls
  - pip install -r requirements.txt
script:
    py.test --pep8 -vv --cov country_converter
after_success:
    coveralls
